// gen-index.mjs - build frontend/src/papers-index.ts from every
// papers/<slug>/paper.json, after validating that each declared \cite id
// resolves to a real source in frontend/src/sources.ts.
//
// The emitted file is committed and imported by the frontend bundle, so it is
// pure data with ZERO pimas imports (Layer A, CLAUDE.md 7). It introduces no
// numbers: it only carries paper metadata already written in the paper.json
// files. Run from inside papers/.
//
// ASCII only, no em-dash (CLAUDE.md 5).

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

// sources.ts has no runtime imports, so Node imports the TypeScript directly (native
// type stripping). Paths resolve relative to this file, so cwd does not matter.
const { sourceById } = await import(new URL("../../frontend/src/sources.ts", import.meta.url).href);

// The papers module root (papers/), one level up from scripts/.
const papersRoot = fileURLToPath(new URL("..", import.meta.url));

// Discover paper.json files: papers/<slug>/paper.json.
const entries = readdirSync(papersRoot, { withFileTypes: true })
  .filter((d) => d.isDirectory() && d.name !== "scripts" && d.name !== "node_modules")
  .map((d) => join(papersRoot, d.name, "paper.json"))
  .filter((p) => existsSync(p));

const papers = [];
let invalid = false;

for (const path of entries) {
  const paper = JSON.parse(readFileSync(path, "utf8"));
  const cites = Array.isArray(paper.cites) ? paper.cites : [];
  for (const id of cites) {
    if (!sourceById(id)) {
      console.error(`gen-index: ${path} cites unknown source id "${id}"`);
      invalid = true;
    }
  }
  papers.push({
    slug: paper.slug,
    title: paper.title,
    authors: (paper.authors || []).map((a) => ({
      name: a.name || "",
      affiliation: a.affiliation || "",
      orcid: a.orcid || "",
    })),
    abstract: paper.abstract || "",
    date: paper.date || "",
    keywords: paper.keywords || [],
    cites,
    pdf: `papers/${paper.slug}.pdf`,
  });
}

if (invalid) {
  console.error("gen-index: aborting; fix the unresolved cite ids above.");
  process.exit(1);
}

// Sort by date descending (newest first).
papers.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

const out = `/**
 * papers-index.ts - GENERATED by papers/scripts/gen-index.mjs. Do not edit by hand.
 *
 * Metadata for every paper under papers/<slug>/. Pure data, zero pimas imports
 * (Layer A, CLAUDE.md 7): the reactive skin reads this list, it never writes it.
 * Every id in each paper's \`cites\` is validated against frontend/src/sources.ts
 * at generation time, so a PaperMeta.cites entry always resolves via sourceById.
 * Regenerate with: npm run gen:index (from papers/).
 */

export interface PaperAuthor {
  name: string;
  affiliation: string;
  orcid: string;
}

export interface PaperMeta {
  slug: string;
  title: string;
  authors: PaperAuthor[];
  abstract: string;
  date: string;
  keywords: string[];
  cites: string[];
  /** Path to the compiled PDF, relative to the site root: papers/<slug>.pdf */
  pdf: string;
}

export const PAPERS: PaperMeta[] = ${JSON.stringify(papers, null, 2)};
`;

const outPath = fileURLToPath(new URL("../../frontend/src/papers-index.ts", import.meta.url));
writeFileSync(outPath, out);
console.log(`gen-index: wrote ${outPath} with ${papers.length} paper(s).`);
