// gen-bib.mjs - generate papers/refs.bib from the project's single bibliography
// source of truth, frontend/src/sources.ts (CLAUDE.md 1, 4).
//
// This script introduces NO numbers of its own: every BibTeX entry mirrors a
// source that already lives in sources.ts, keyed by that source's `id` so a
// \cite{williams-ayres-heller-2002} in a paper matches the site's Cite id.
//
// sources.ts is TypeScript with no runtime imports, so Node (>=22.6, native type
// stripping) imports it directly - no build step and no reaching into another
// module's toolchain. Paths are resolved relative to this file (import.meta.url), so
// the script runs correctly from any working directory.
//
// ASCII only, no em-dash (CLAUDE.md 5).

import { writeFileSync } from "node:fs";

const { SOURCES } = await import(new URL("../../frontend/src/sources.ts", import.meta.url).href);

/** Escape the four BibTeX-special characters. Backslash is never introduced by data. */
function esc(s) {
  return String(s).replace(/([&%#_])/g, "\\$1");
}

/**
 * Convert an author DISPLAY string into BibTeX's "A and B and C" form.
 *
 * The display strings in sources.ts intentionally carry affiliations, "(eds.)",
 * "et al.", and name suffixes ("Jr.", "III"). BibTeX's own name parser mangles
 * all of these (it reads "Jr." as a surname, splits "(Los Alamos ...)" into fake
 * initials, etc.). So we do NOT let BibTeX parse names: we strip the parts that
 * must never enter the author field, then brace-wrap each remaining author token
 * as a single opaque literal so BibTeX prints it verbatim, in order, with no
 * initial-abbreviation or surname reordering.
 *
 * Applied before esc(), so any "&" here is still a literal separator; after the
 * split there are no "&" left in the output.
 */
function authorsToBib(authors) {
  // 1. Strip parenthetical groups (affiliations, "(eds.)", "(ed.)") and collapse
  //    the whitespace they leave behind. These must never enter the author field.
  let s = String(authors)
    .replace(/\s*\([^)]*\)/g, "")
    .replace(/\s+/g, " ")
    .trim();

  // 2. Detect a trailing "et al." (now that parentheticals are gone). Remove it
  //    and remember to append BibTeX's "and others", which IEEEtran renders as
  //    "et al.".
  let hasEtAl = false;
  const etAl = s.replace(/\s*\bet al\.?\s*$/i, "");
  if (etAl !== s) {
    hasEtAl = true;
    s = etAl.trim();
  }

  // 3. Split on the existing separators into individual author tokens.
  // 4. Brace-wrap each non-empty token so BibTeX treats it as one literal and
  //    prints it verbatim. Drop empty tokens (e.g. a trailing separator).
  const tokens = s
    .split(/\s*[&;,]\s*/)
    .map((t) => t.trim())
    .filter((t) => t.length > 0)
    .map((t) => `{${t}}`);

  // 5. Join with " and ", appending " and others" when the et al. flag fired.
  if (hasEtAl) tokens.push("others");
  return tokens.join(" and ");
}

/**
 * Pick an entry type from the venue text. Order matters: the more specific
 * tests run first. This is a heuristic over free-text venues, not a schema.
 */
function entryType(venue) {
  const v = String(venue);
  if (/textbook|isbn/i.test(v)) return "book";
  if (/nasa|ntrs|report|technical/i.test(v)) return "techreport";
  if (/\brfc\b|\biau\b|astm|codata|standard/i.test(v)) return "misc";
  const looksJournal =
    /journal|transactions|trans\.|review|letters|\bnature\b|pnas|geophys|acta|astronom|env\.|environmental|\bj\.\b|doi|\d+\s*\(\d+\)|\d+:\d+/i.test(
      v,
    );
  return looksJournal ? "article" : "misc";
}

/** The venue field name that carries the "where published" text for each type. */
const VENUE_FIELD = {
  article: "journal",
  book: "publisher",
  techreport: "institution",
  misc: "howpublished",
};

function toBibEntry(src) {
  const type = entryType(src.venue);
  const lines = [];
  lines.push(`@${type}{${src.id},`);
  // Title in braces so BibTeX preserves capitalization.
  lines.push(`  title = {{${esc(src.title)}}},`);
  lines.push(`  author = {${esc(authorsToBib(src.authors))}},`);
  lines.push(`  year = {${esc(src.year)}},`);
  const venueField = VENUE_FIELD[type];
  if (src.venue) lines.push(`  ${venueField} = {${esc(src.venue)}},`);
  if (src.url) lines.push(`  url = {${src.url}},`);
  // A note only where it adds something: flag entries the repo cites by
  // reference with no online link, so the gap is visible in the .bib too.
  if (!src.url) lines.push(`  note = {Cited by reference; no online link.},`);
  lines.push(`}`);
  return lines.join("\n");
}

const header = [
  "% refs.bib - GENERATED by papers/scripts/gen-bib.mjs. Do not edit by hand.",
  "% Every entry mirrors a source in frontend/src/sources.ts (the single",
  "% bibliography source of truth). Regenerate with: npm run gen:bib",
  "",
  "",
].join("\n");

const body = SOURCES.map(toBibEntry).join("\n\n");
writeFileSync(new URL("../refs.bib", import.meta.url), header + body + "\n");
console.log(`gen-bib: wrote refs.bib with ${SOURCES.length} entries.`);
