"""Low-discrepancy sequences - Halton and Sobol', deterministic and pure Python.

Monte Carlo places samples at random and its integration error falls only as
1/sqrt(N). A *low-discrepancy* (quasi-random) sequence places them to fill the unit
cube far more evenly, so for a smooth, low-to-moderate-dimensional integrand the
error falls close to 1/N - a large win at the small sample counts this repo's
findings live at. This module is the shared source of those sequences; the QMC mean
estimator ([[qmc]]) and the Saltelli/Sobol sensitivity design ([[sobol]]) both draw
their base points here instead of re-rolling a sampler.

Two sequences, one job each:

- **Halton** - per-dimension van der Corput (radical-inverse) points in the first
  primes as bases. Trivial to generate, good in low dimension; the high-prime bases
  correlate as dimension grows, which is exactly why Sobol' exists.
- **Sobol'** - a digital (t, s)-sequence with far better high-dimensional
  equidistribution. Built from the Joe & Kuo (2008) direction numbers, generated by
  the standard gray-code recurrence.

Scope (what this module is and is NOT):
  - IS: pure functions returning points in [0, 1)^d. `radical_inverse`, `halton_point`,
    `sobol_points`. Deterministic - the same (n, dim) always returns byte-identical
    points, no seed, no wall clock (CLAUDE.md §7). This is the un-randomized sequence.
  - IS NOT: the *randomization* (Cranley-Patterson shift / Owen scramble) that turns a
    quasi-random sequence into an estimator with an honest error bar - that lives with
    the estimators in [[qmc]], because the seed and the replicate loop are theirs. Nor
    does it push points through a distribution's inverse CDF; callers do that.

Provenance and the no-invented-numbers rule (CLAUDE.md §1): the Sobol' direction
integers below are not tunable and not guessed. They are the Joe & Kuo (2008) values
as distributed with SciPy (BSD-3), transcribed here so the runtime needs no SciPy,
and pinned by `tests/test_sequences.py`, which regenerates them from
`scipy.stats.qmc.Sobol` and asserts this module's points are bit-identical. A drift in
the table is a test failure, not a silent bad sequence - the same discipline the RNG's
JS-parity fixture holds. See REFERENCES.md.
"""

from __future__ import annotations

import math

# First primes, the per-dimension Halton bases. Matches the Sobol' dimension cap so a
# caller can move between the two sequences without changing how many inputs it has.
_PRIMES: tuple[int, ...] = (
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73,
)

MAX_HALTON_DIM = len(_PRIMES)


# --- Halton ---------------------------------------------------------------------


def radical_inverse(i: int, base: int) -> float:
    """Base-``base`` radical inverse of ``i`` - the 1-D van der Corput value in [0, 1).

    Reflects the base-``base`` digits of ``i`` about the radix point: i = sum d_k
    base^k maps to sum d_k base^(-k-1). ``radical_inverse(0, b)`` is 0.
    """
    if base < 2:
        raise ValueError(f"radical_inverse base must be >= 2, got {base}")
    if i < 0:
        raise ValueError(f"radical_inverse index must be >= 0, got {i}")
    f = 1.0
    r = 0.0
    while i > 0:
        f /= base
        r += f * (i % base)
        i //= base
    return r


def halton_point(index: int, dim: int) -> tuple[float, ...]:
    """The Halton point at ``index`` (>= 0) in ``dim`` dimensions, in [0, 1)^dim.

    Dimension d uses the (d+1)-th prime as its radical-inverse base. ``index=0`` is
    the origin; callers typically start at 1 to avoid sampling the cube corner.
    """
    if dim < 1 or dim > MAX_HALTON_DIM:
        raise ValueError(f"halton_point dim must be in [1, {MAX_HALTON_DIM}], got {dim}")
    if index < 0:
        raise ValueError(f"halton_point index must be >= 0, got {index}")
    return tuple(radical_inverse(index, _PRIMES[d]) for d in range(dim))


# --- Sobol' ---------------------------------------------------------------------

# Bit depth of the direction numbers: points are integers in [0, 2**30) scaled by
# 2**-30, matching SciPy's default. 2**30 ~ 1.07e9 points before the sequence repeats
# - vastly more than any sample count this repo runs.
_SOBOL_BITS = 30
_SOBOL_SCALE = 1.0 / (1 << _SOBOL_BITS)

# Number of dimensions the embedded direction table supports. Dimension 1 is the
# trivial van der Corput column (generated in code); dims 2..21 are tabulated.
MAX_SOBOL_DIM = 21

# Direction integers V[dim][bit] for Sobol' dimensions 2..21 (dimension 1 is the
# trivial column 1<<(_SOBOL_BITS-1-bit), added in code). Joe & Kuo (2008) direction
# numbers as distributed with SciPy (BSD-3); regenerated and bit-verified by
# tests/test_sequences.py. See REFERENCES.md. Do not hand-edit - these are not tunable.
_SOBOL_V: tuple[tuple[int, ...], ...] = (
    (536870912, 805306368, 671088640, 1006632960, 570425344, 855638016, 713031680, 1069547520, 538968064, 808452096, 673710080, 1010565120, 572653568, 858980352, 715816960, 1073725440, 536879104, 805318656, 671098880, 1006648320, 570434048, 855651072, 713042560, 1069563840, 538976288, 808464432, 673720360, 1010580540, 572662306, 858993459),
    (536870912, 805306368, 402653184, 603979776, 973078528, 385875968, 595591168, 826277888, 438304768, 657457152, 999817216, 358875136, 538574848, 807862272, 406552576, 605372416, 975183872, 389033984, 597170176, 828646400, 437926400, 656873216, 1002152832, 357921088, 536885792, 805312304, 402662296, 603992420, 973085210, 385885991),
    (536870912, 805306368, 134217728, 335544320, 1040187392, 486539264, 679477248, 616562688, 908066816, 156237824, 376963072, 968097792, 503447552, 755171328, 545292288, 817971200, 136568832, 340905984, 1056606208, 494291968, 673276416, 609457408, 922347392, 158784320, 371195936, 961544240, 511180808, 766771220, 537002046, 805503005),
    (536870912, 268435456, 134217728, 738197504, 1040187392, 922746880, 511705088, 658505728, 379584512, 200278016, 676855808, 1009516544, 916586496, 468779008, 542670848, 271499264, 144826368, 754085888, 1054435328, 929870848, 503351808, 654495488, 377744768, 188970688, 681697312, 1022521360, 920217608, 460108844, 536906302, 268619575),
    (536870912, 268435456, 402653184, 201326592, 838860800, 150994944, 360710144, 1052770304, 941621248, 470810624, 706215936, 84672512, 665976832, 935919616, 766869504, 586072064, 301998080, 419434496, 226498560, 851446784, 169882112, 353372416, 1066931584, 1003241152, 529676320, 735648784, 128821784, 669173004, 900859826, 784934857),
    (536870912, 805306368, 671088640, 872415232, 369098752, 620756992, 260046848, 952107008, 799014912, 149946368, 126353408, 1019478016, 295567360, 434176000, 504463360, 555335680, 832446464, 702623744, 907126784, 354022400, 664679936, 216077568, 965846912, 769248448, 138287520, 68230640, 1041866760, 287174660, 429918270, 502268945),
    (536870912, 268435456, 671088640, 335544320, 570425344, 150994944, 75497472, 188743680, 497025024, 663748608, 34078720, 419692544, 747241472, 524615680, 1068007424, 781336576, 109649920, 306630656, 825059328, 954000384, 1033896448, 932184320, 705168000, 218366272, 243925536, 373620880, 992510024, 634536116, 455680474, 903271033),
    (536870912, 268435456, 671088640, 335544320, 167772160, 889192448, 444596224, 473956352, 236978176, 370147328, 981991424, 205783040, 640286720, 34930688, 814383104, 961101824, 1017946112, 508694528, 1051265024, 794608640, 103416320, 303366400, 411730560, 759775552, 917282976, 726799184, 606669224, 857523652, 134873826, 67436641),
    (536870912, 268435456, 939524096, 738197504, 637534208, 620756992, 578813952, 381681664, 216006656, 913309696, 478674944, 264503296, 812515328, 700121088, 350322688, 175980544, 42901504, 113946624, 887404544, 444587008, 982385152, 717947136, 317293440, 1064911552, 402694752, 1006744144, 504183336, 151428460, 76456654, 868921959),
    (536870912, 268435456, 671088640, 67108864, 33554432, 452984832, 662700032, 146800640, 367001600, 728760320, 535298048, 611581952, 308412416, 867500032, 570589184, 184795136, 260268032, 214298624, 401348608, 813575168, 946037248, 750121216, 126098048, 415902784, 1038180896, 795930800, 502175992, 1065217228, 903873406, 997196295),
    (536870912, 268435456, 134217728, 201326592, 369098752, 721420288, 629145600, 180355072, 891289600, 38797312, 950534144, 345243648, 327811072, 835125248, 413630464, 77185024, 461692928, 1036808192, 245770240, 798041088, 1041162752, 923496704, 998353024, 768140480, 111805280, 597099440, 672105176, 470663276, 504291890, 655061653),
    (536870912, 805306368, 671088640, 335544320, 1040187392, 587202560, 947912704, 213909504, 65011712, 139460608, 627572736, 396099584, 906100736, 118030336, 780500992, 1003339776, 90284032, 664530944, 503764992, 319628288, 277062144, 415429376, 1038834304, 727508288, 501219808, 458228016, 904397064, 257687948, 199361502, 744030901),
    (536870912, 805306368, 402653184, 603979776, 234881024, 822083584, 276824064, 683671552, 1012924416, 714080256, 1060634624, 558104576, 939655168, 335740928, 369197056, 352468992, 511762432, 432214016, 752945152, 38964224, 56346112, 198617344, 121238400, 893719616, 771751968, 16777264, 142606360, 213909540, 845152270, 462422065),
    (536870912, 268435456, 134217728, 1006632960, 704643072, 352321536, 645922816, 658505728, 127926272, 389021696, 524812288, 591659008, 153223168, 477167616, 988315648, 494387200, 451452928, 225726464, 317253632, 829731840, 954751488, 611771136, 510377088, 53989440, 432709664, 335892496, 109078536, 927167548, 262208042, 724742933),
    (536870912, 805306368, 134217728, 872415232, 905969664, 822083584, 293601280, 557842432, 694157312, 498073600, 728236032, 447479808, 191496192, 716111872, 57311232, 514605056, 896131072, 800018432, 619247616, 250430464, 227175936, 324837120, 652269696, 166802880, 764046880, 593272624, 786487432, 1039218164, 462056982, 308059905),
    (536870912, 268435456, 134217728, 1006632960, 234881024, 83886080, 1031798784, 432013312, 601882624, 336592896, 581435392, 66846720, 78249984, 721223680, 1059749888, 171884544, 793403392, 49188864, 327268352, 214109184, 375490048, 835931392, 256584832, 317502144, 461473312, 818105616, 409152648, 886092540, 852198958, 187583765),
    (536870912, 805306368, 134217728, 1006632960, 436207616, 419430400, 226492416, 457179136, 274726912, 940572672, 884473856, 654049280, 54132736, 348061696, 383418368, 200065024, 671293440, 201412608, 302118912, 621011968, 394296832, 37987584, 501388672, 592468672, 618298912, 518825264, 931141000, 843094780, 367222330, 525530409),
    (536870912, 268435456, 671088640, 335544320, 637534208, 1023410176, 729808896, 784334848, 970981376, 628097024, 117964800, 873201664, 921305088, 360513536, 1071677440, 141574144, 76079104, 248418304, 688576512, 218905600, 325690880, 314374912, 193007232, 1052936128, 299976224, 829582096, 554423976, 151960532, 493412358, 1002344493),
    (536870912, 805306368, 939524096, 738197504, 771751936, 251658240, 864026624, 272629760, 140509184, 342884352, 39321600, 559677440, 1016987648, 598147072, 402685952, 469811200, 369156096, 587247616, 494974976, 524303360, 1004588544, 70271232, 171450752, 892096960, 1053165920, 50038128, 614363768, 1067929244, 234881026, 1056964611),
    (536870912, 805306368, 939524096, 872415232, 436207616, 251658240, 578813952, 339738624, 710934528, 930086912, 384303104, 242483200, 629014528, 364183552, 41975808, 608223232, 308338688, 57724928, 216557568, 24394752, 134121984, 32854272, 685779328, 321920448, 76069792, 218425808, 697761272, 348220116, 92143618, 632619011),
)


def _sobol_direction(dim: int) -> list[list[int]]:
    """Direction integers per active dimension: [dim][bit], bit 0..._SOBOL_BITS-1.

    Dimension 1 (index 0) is the trivial van der Corput column 1<<(BITS-1-bit); the
    remaining dims come straight from the tabulated Joe-Kuo values.
    """
    dirs: list[list[int]] = [[1 << (_SOBOL_BITS - 1 - b) for b in range(_SOBOL_BITS)]]
    for d in range(1, dim):
        dirs.append(list(_SOBOL_V[d - 1]))
    return dirs


def sobol_points(n: int, dim: int, *, skip: int = 0) -> list[tuple[float, ...]]:
    """The first ``n`` Sobol' points (after ``skip``) in ``dim`` dimensions, in [0, 1)^dim.

    Generated in natural index order by the gray-code recurrence: point i differs
    from point i-1 by XOR-ing one direction integer per dimension, which is both
    fast and exactly the construction SciPy uses (so the two are bit-identical - see
    the oracle test). Point 0 is the origin (all zeros); pass ``skip=1`` to drop it,
    or a larger skip to advance into the sequence. Deterministic: no seed, no clock.
    """
    if dim < 1 or dim > MAX_SOBOL_DIM:
        raise ValueError(f"sobol_points dim must be in [1, {MAX_SOBOL_DIM}], got {dim}")
    if n < 0:
        raise ValueError(f"sobol_points n must be >= 0, got {n}")
    if skip < 0:
        raise ValueError(f"sobol_points skip must be >= 0, got {skip}")
    total = skip + n
    if total > (1 << _SOBOL_BITS):
        raise ValueError(
            f"sobol_points: skip+n={total} exceeds the {1 << _SOBOL_BITS}-point capacity "
            f"of {_SOBOL_BITS}-bit direction numbers"
        )
    dirs = _sobol_direction(dim)
    out: list[tuple[float, ...]] = []
    x = [0] * dim
    # Emit index 0 (origin) explicitly, then advance via gray code.
    if skip == 0 and n > 0:
        out.append(tuple(0.0 for _ in range(dim)))
    for i in range(1, total):
        # Column c-1 is the position of the lowest zero bit of (i-1); equivalently the
        # count of trailing one-bits of (i-1). This is the gray-code transition column.
        c = 1
        v = i - 1
        while v & 1:
            v >>= 1
            c += 1
        col = c - 1
        for d in range(dim):
            x[d] ^= dirs[d][col]
        if i >= skip:
            out.append(tuple(x[d] * _SOBOL_SCALE for d in range(dim)))
    return out


__all__ = [
    "MAX_HALTON_DIM",
    "MAX_SOBOL_DIM",
    "halton_point",
    "radical_inverse",
    "sobol_points",
]
