/**
 * Layer A (pimas-free) tests for the papers index. The papers surface lists LaTeX
 * write-ups whose bibliographies are generated from the same SOURCES list that powers
 * the site's citations, so the load-bearing invariant is: every id a paper cites must
 * resolve in the bibliography. If a paper.json cites an id that does not exist (a typo,
 * or a source later removed), that is caught here rather than shipping a dead citation.
 * papers-index.ts is generated by papers/scripts/gen-index.mjs; these tests guard the
 * committed result.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { sourceById } from "./sources.ts";
// The list is generated by papers/scripts/gen-index.mjs; node's test loader reads the .ts.
import { PAPERS as PAPERS_INDEX } from "./papers-index.ts";

test("papers-index loads and has at least one paper", () => {
  assert.ok(Array.isArray(PAPERS_INDEX), "PAPERS is not an array");
  assert.ok(PAPERS_INDEX.length >= 1, "expected at least one paper");
});

test("every paper is complete (no empty required fields)", () => {
  for (const p of PAPERS_INDEX) {
    for (const [k, v] of Object.entries({ slug: p.slug, title: p.title, abstract: p.abstract, date: p.date, pdf: p.pdf })) {
      assert.ok(typeof v === "string" && v.trim().length > 0, `${p.slug}: empty ${k}`);
    }
    assert.ok(Array.isArray(p.authors) && p.authors.length > 0, `${p.slug}: no authors`);
    for (const a of p.authors) assert.ok(a.name && a.name.trim().length > 0, `${p.slug}: author with no name`);
    assert.ok(Array.isArray(p.keywords) && p.keywords.length > 0, `${p.slug}: no keywords`);
    assert.ok(Array.isArray(p.cites) && p.cites.length > 0, `${p.slug}: cites nothing`);
  }
});

test("every cited id resolves in the bibliography (no dead citations)", () => {
  for (const p of PAPERS_INDEX) {
    for (const id of p.cites) {
      assert.ok(sourceById(id), `${p.slug}: cites unknown source id "${id}"`);
    }
  }
});

test("pdf path matches the slug convention", () => {
  for (const p of PAPERS_INDEX) {
    assert.equal(p.pdf, `papers/${p.slug}.pdf`, `${p.slug}: pdf path mismatch (${p.pdf})`);
  }
});

test("dates are ISO YYYY-MM-DD and slugs are unique", () => {
  const slugs = PAPERS_INDEX.map((p) => p.slug);
  assert.equal(new Set(slugs).size, slugs.length, "duplicate paper slug");
  for (const p of PAPERS_INDEX) {
    assert.match(p.date, /^\d{4}-\d{2}-\d{2}$/, `${p.slug}: date not ISO YYYY-MM-DD`);
  }
});

test("no em-dash or emoji in paper metadata (typography rule)", () => {
  const emdash = /—/;
  const emoji = /[\u{1F000}-\u{1FAFF}\u{2600}-\u{26FF}\u{2705}\u{2714}\u{2717}\u{274C}]/u;
  for (const p of PAPERS_INDEX) {
    const blob = `${p.title} ${p.abstract} ${p.keywords.join(" ")} ${p.authors.map((a) => a.name + " " + a.affiliation).join(" ")}`;
    assert.ok(!emdash.test(blob), `${p.slug}: contains an em-dash`);
    assert.ok(!emoji.test(blob), `${p.slug}: contains an emoji`);
  }
});
