/**
 * papers-index.ts - GENERATED by papers/scripts/gen-index.mjs. Do not edit by hand.
 *
 * Metadata for every paper under papers/<slug>/. Pure data, zero pimas imports
 * (Layer A, CLAUDE.md 7): the reactive skin reads this list, it never writes it.
 * Every id in each paper's `cites` is validated against frontend/src/sources.ts
 * at generation time, so a PaperMeta.cites entry always resolves via sourceById.
 * Regenerate with: npm run gen:index (from papers/).
 */

export interface PaperAuthor {
  name: string;
  affiliation: string;
  orcid: string;
}

export interface PaperMeta {
  slug: string;
  title: string;
  authors: PaperAuthor[];
  abstract: string;
  date: string;
  keywords: string[];
  cites: string[];
  /** Path to the compiled PDF, relative to the site root: papers/<slug>.pdf */
  pdf: string;
}

export const PAPERS: PaperMeta[] = [
  {
    "slug": "coordination-tax",
    "title": "The Coordination Tax Is Paid in Fuel, Not Time: Light-Speed Delay in a Self-Replicating Probe Swarm",
    "authors": [
      {
        "name": "Noah Hydén",
        "affiliation": "Independent researcher",
        "orcid": "0009-0003-4523-0467"
      }
    ],
    "abstract": "A swarm of self-replicating probes fills a stellar field star by star, each probe settling a star and launching copies. The standard exploration-timescale model grants every probe perfect, instantaneous knowledge of which stars are already settled, and names finite light-speed as its own future work. We add that light-speed limit and measure its cost, and the first finding is a caution: a model advanced in a timestep coarser than the interval between probe launches makes many probes decide from the same stale snapshot at once, and the resulting collisions appear to slow the fill of the field by tens of percent. They do not. Resolved so that each probe decides at its true arrival time, light-speed lag does not measurably delay the fill, and the gravitational-slingshot speed-up survives contact with finite information, reproducing the source model quantitatively at about 166 times powered flight. The real cost lies elsewhere. The field is always filled, with a negligible change in the number of probes built; what the delay changes is the number of wasted journeys the swarm flies to stars other probes have already claimed. That is a tax in fuel and effort, not time, and it is governed cleanly by the probe's speed in units of the speed of light: a median of about 0.7 percent of journeys at slingshot speeds, rising monotonically to about 18 percent at the directed-energy speeds beamed-propulsion concepts target, positive in all 32 seeds of a paired ensemble and a roughly scale-independent fraction of effort across a four-fold range of field sizes. Gravitational slingshots self-limit well below the speeds where the tax bites, so the cost falls specifically on fast, driven probes; and because the kinetic cost of a wasted hop grows with speed, the tax is heavier still as a fraction of the energy budget. The coordination cost a perfect-information model hides is paid in fuel, not time, and it scales with how fast the swarm flies.",
    "date": "2026-07-09",
    "keywords": [
      "self-replication",
      "interstellar exploration",
      "light-speed delay",
      "multi-agent coordination",
      "directed-energy propulsion"
    ],
    "cites": [
      "hart-1975",
      "tipler-1980",
      "freitas-1980-interstellar-probe",
      "newman-sagan-1981",
      "jones-1981",
      "bjork-2007",
      "cotta-morales-2009",
      "forgan-2009",
      "forgan-papadog-kitching-2013",
      "nicholson-forgan-2013",
      "lubin-2016",
      "carroll-nellenback-2019",
      "lamport-1978",
      "recons-census",
      "kerr-lynden-bell-1986",
      "nordstrom-2004-gcs",
      "olfati-saber-murray-2004",
      "olfati-saber-fax-murray-2007",
      "flp-1985",
      "gilbert-lynch-2002",
      "ferrell-1965",
      "sheridan-1993",
      "burleigh-2003",
      "rfc-4838",
      "rfc-9171"
    ],
    "pdf": "papers/coordination-tax.pdf"
  },
  {
    "slug": "electronics-wall",
    "title": "The Electronics Wall: Why a Self-Replicating Space Factory Cannot Close on Its Own Chips",
    "authors": [
      {
        "name": "Noah Hydén",
        "affiliation": "Independent researcher",
        "orcid": "0009-0003-4523-0467"
      }
    ],
    "abstract": "A self-replicating space factory lands with a fixed cargo and builds copies of itself from local material. Its promise is leverage: the fraction of its own mass it can remake locally, its closure, sets how much installed capacity each launched kilogram becomes, exactly 1/(1-C). We show why that fraction stops short of one at a wall built of chips. The wall is twofold. Chips sit at the end of the deepest supply chain on Earth, and they are staggeringly energy-hungry to make, with an embodied energy roughly three orders of magnitude above smelted metal. Modern seed-factory studies converge on achievable closure near 70 to 96 percent and agree that chasing 100 percent is not worthwhile, so imported electronics are a permanent design feature rather than a temporary compromise. Letting a highly closed seed make its own chips pays off only when it is also swimming in power; starved of power it backfires. Imported electronics, and the launch-mass leverage they cap, are therefore intrinsic to the concept.",
    "date": "2026-07-09",
    "keywords": [
      "self-replication",
      "in-situ manufacturing",
      "material closure",
      "embodied energy",
      "space systems"
    ],
    "cites": [
      "von-neumann-burks-1966",
      "nasa-cp-2255-1980",
      "freitas-merkle-2004",
      "chirikjian-2004-niac",
      "moses-chirikjian-2020",
      "zykov-lipson-2005",
      "reprap-jones-2011",
      "borgue-hein-2020",
      "metzger-2013",
      "guided-self-replicating-factory-2021",
      "csis-semiconductor-supply-chain",
      "williams-ayres-heller-2002",
      "nagapurkar-das-2022",
      "gutowski-2009",
      "boyd-2012",
      "murphy-2003",
      "ice-coefficients",
      "ashby-2012",
      "peng-2013-pv-lca",
      "power-electronics-lca",
      "sensor-embodied-2021",
      "guerrero-zabel-2023",
      "tsiolkovsky-1903",
      "sutton-biblarz-2016",
      "curtis-2020",
      "jones-2018-launch-cost"
    ],
    "pdf": "papers/electronics-wall.pdf"
  }
];
