/**
 * Layer A (pimas-free) tests for the papers index. The papers surface lists LaTeX
 * write-ups whose bibliographies are generated from the same SOURCES list that powers
 * the site's citations, so the load-bearing invariant is: every id a paper cites must
 * resolve in the bibliography. If a paper.json cites an id that does not exist (a typo,
 * or a source later removed), that is caught here rather than shipping a dead citation.
 * papers-index.ts is generated by papers/scripts/gen-index.mjs; these tests guard the
 * committed result.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { sourceById } from "./sources.ts";
// The list is generated by papers/scripts/gen-index.mjs; node's test loader reads the .ts.
import { PAPERS as PAPERS_INDEX } from "./papers-index.ts";

test("papers-index loads and has at least one paper", () => {
  assert.ok(Array.isArray(PAPERS_INDEX), "PAPERS is not an array");
  assert.ok(PAPERS_INDEX.length >= 1, "expected at least one paper");
});

test("every paper is complete (no empty required fields)", () => {
  for (const p of PAPERS_INDEX) {
    for (const [k, v] of Object.entries({ slug: p.slug, title: p.title, abstract: p.abstract, date: p.date, pdf: p.pdf })) {
      assert.ok(typeof v === "string" && v.trim().length > 0, `${p.slug}: empty ${k}`);
    }
    assert.ok(Array.isArray(p.authors) && p.authors.length > 0, `${p.slug}: no authors`);
    for (const a of p.authors) assert.ok(a.name && a.name.trim().length > 0, `${p.slug}: author with no name`);
    assert.ok(Array.isArray(p.keywords) && p.keywords.length > 0, `${p.slug}: no keywords`);
    assert.ok(Array.isArray(p.cites) && p.cites.length > 0, `${p.slug}: cites nothing`);
  }
});

test("every cited id resolves in the bibliography (no dead citations)", () => {
  for (const p of PAPERS_INDEX) {
    for (const id of p.cites) {
      assert.ok(sourceById(id), `${p.slug}: cites unknown source id "${id}"`);
    }
  }
});

test("pdf path matches the slug convention", () => {
  for (const p of PAPERS_INDEX) {
    assert.equal(p.pdf, `papers/${p.slug}.pdf`, `${p.slug}: pdf path mismatch (${p.pdf})`);
  }
});

test("doi field is well-formed (null until minted; sandbox flagged)", () => {
  for (const p of PAPERS_INDEX) {
    assert.ok(p.doi === null || typeof p.doi === "string", `${p.slug}: doi is neither null nor string`);
    assert.equal(typeof p.doiIsSandbox, "boolean", `${p.slug}: doiIsSandbox is not a boolean`);
    // A sandbox flag is meaningless without a DOI to flag.
    if (p.doiIsSandbox) assert.ok(p.doi, `${p.slug}: doiIsSandbox true but doi is empty`);
  }
});

// The version manifest (papers-versions.ts) is generated from git history at build
// time and is gitignored, so it may be absent when `npm test` runs before a build
// (the CI frontend job does exactly that). Import it defensively: if present, its
// shape must hold; if absent, this test is a no-op rather than a load failure.
test("version manifest, when generated, is well-formed", async () => {
  let PAPER_VERSIONS: Record<string, Array<Record<string, unknown>>> | null = null;
  try {
    ({ PAPER_VERSIONS } = await import("./papers-versions.ts"));
  } catch {
    return; // not generated in this environment; nothing to assert
  }
  assert.ok(PAPER_VERSIONS && typeof PAPER_VERSIONS === "object", "PAPER_VERSIONS is not an object");
  const slugs = new Set(PAPERS_INDEX.map((p) => p.slug));
  for (const [slug, versions] of Object.entries(PAPER_VERSIONS)) {
    assert.ok(slugs.has(slug), `version manifest names unknown paper slug "${slug}"`);
    assert.ok(Array.isArray(versions), `${slug}: versions is not an array`);
    for (const v of versions) {
      assert.match(String(v.shortSha), /^[0-9a-f]{7,}$/, `${slug}: bad shortSha "${v.shortSha}"`);
      assert.match(String(v.date), /^\d{4}-\d{2}-\d{2}$/, `${slug}: version date not ISO (${v.date})`);
      assert.equal(v.pdf, `papers/${slug}/${v.shortSha}.pdf`, `${slug}: version pdf path mismatch (${v.pdf})`);
      assert.equal(typeof v.hasPdf, "boolean", `${slug}: hasPdf is not a boolean`);
      assert.ok(String(v.sourceUrl).startsWith("https://github.com/"), `${slug}: bad sourceUrl`);
    }
  }
});

test("dates are ISO YYYY-MM-DD and slugs are unique", () => {
  const slugs = PAPERS_INDEX.map((p) => p.slug);
  assert.equal(new Set(slugs).size, slugs.length, "duplicate paper slug");
  for (const p of PAPERS_INDEX) {
    assert.match(p.date, /^\d{4}-\d{2}-\d{2}$/, `${p.slug}: date not ISO YYYY-MM-DD`);
  }
});

test("no em-dash or emoji in paper metadata (typography rule)", () => {
  const emdash = /—/;
  const emoji = /[\u{1F000}-\u{1FAFF}\u{2600}-\u{26FF}\u{2705}\u{2714}\u{2717}\u{274C}]/u;
  for (const p of PAPERS_INDEX) {
    const blob = `${p.title} ${p.abstract} ${p.keywords.join(" ")} ${p.authors.map((a) => a.name + " " + a.affiliation).join(" ")}`;
    assert.ok(!emdash.test(blob), `${p.slug}: contains an em-dash`);
    assert.ok(!emoji.test(blob), `${p.slug}: contains an emoji`);
  }
});
