/**
 * papers-index.ts - GENERATED by papers/scripts/gen-index.mjs. Do not edit by hand.
 *
 * Metadata for every paper under papers/<slug>/. Pure data, zero pimas imports
 * (Layer A, CLAUDE.md 7): the reactive skin reads this list, it never writes it.
 * Every id in each paper's `cites` is validated against frontend/src/sources.ts
 * at generation time, so a PaperMeta.cites entry always resolves via sourceById.
 * Regenerate with: npm run gen:index (from papers/).
 */

export interface PaperAuthor {
  name: string;
  affiliation: string;
  orcid: string;
}

export interface PaperMeta {
  slug: string;
  title: string;
  authors: PaperAuthor[];
  abstract: string;
  date: string;
  keywords: string[];
  cites: string[];
  /** Path to the compiled PDF, relative to the site root: papers/<slug>.pdf */
  pdf: string;
}

export const PAPERS: PaperMeta[] = [
  {
    "slug": "coordination-tax",
    "title": "The Coordination Tax: Light-Speed Delay in a Self-Replicating Probe Swarm Bites Only When Hops Are Long",
    "authors": [
      {
        "name": "Noah Hydén",
        "affiliation": "Independent researcher",
        "orcid": "0009-0003-4523-0467"
      }
    ],
    "abstract": "A swarm of self-replicating probes fills a stellar field star by star, each settling a star and launching copies. The standard exploration-timescale model grants every probe perfect, instantaneous knowledge of which stars are already settled; finite light-speed is its stated future work. We add that light-speed limit: a probe deciding at a star treats a distant star as settled only once the news, travelling at c, has arrived, so probes race for the same target from stale views and waste trips. Over a 32-seed paired ensemble on identical galaxies, the delay slows the time to fill the field by a median of about 0 percent for powered nearest-neighbour flight, about 30 percent for nearest-star slingshot flight, and about 50 percent for maximum-boost slingshot flight; every case still reaches 100 percent, so lag alone produces no permanent unsettled fraction. The lag scale is set by the dimensionless ratio of information-delay to travel-time per hop, which equals the probe speed in units of c; whether it actually bites is decided by how non-local each hop is. Fast but local flight is nearly immune, because a probe that loses a race simply takes the star next door; the cost falls on long-range hops made from stale views. This refines the perfect-information picture: the slingshot speed-up is real, but under finite light-speed a meaningful fraction of it is eaten by uncoordinated long-range collisions.",
    "date": "2026-07-08",
    "keywords": [
      "self-replication",
      "interstellar exploration",
      "light-speed delay",
      "multi-agent coordination",
      "swarm dynamics"
    ],
    "cites": [
      "nicholson-forgan-2013",
      "forgan-papadog-kitching-2013",
      "olfati-saber-murray-2004",
      "ferrell-1965",
      "rfc-4838"
    ],
    "pdf": "papers/coordination-tax.pdf"
  },
  {
    "slug": "electronics-wall",
    "title": "The Electronics Wall: Why a Self-Replicating Space Factory Cannot Close on Its Own Chips",
    "authors": [
      {
        "name": "Noah Hydén",
        "affiliation": "Independent researcher",
        "orcid": "0009-0003-4523-0467"
      }
    ],
    "abstract": "A self-replicating space factory lands with a fixed cargo and builds copies of itself from local material. Its promise is leverage: the fraction of its own mass it can remake locally, its closure, sets how much installed capacity each launched kilogram becomes, exactly 1/(1-C). We show why that fraction stops short of one at a wall built of chips. The wall is twofold. Chips sit at the end of the deepest supply chain on Earth, and they are staggeringly energy-hungry to make, with an embodied energy roughly three orders of magnitude above smelted metal. Modern seed-factory studies converge on achievable closure near 70 to 96 percent and agree that chasing 100 percent is not worthwhile, so imported electronics are a permanent design feature rather than a temporary compromise. Letting a highly closed seed make its own chips pays off only when it is also swimming in power; starved of power it backfires. Imported electronics, and the launch-mass leverage they cap, are therefore intrinsic to the concept.",
    "date": "2026-07-07",
    "keywords": [
      "self-replication",
      "in-situ manufacturing",
      "material closure",
      "embodied energy",
      "space systems"
    ],
    "cites": [
      "nasa-cp-2255-1980",
      "williams-ayres-heller-2002",
      "nagapurkar-das-2022",
      "freitas-merkle-2004",
      "guided-self-replicating-factory-2021",
      "csis-semiconductor-supply-chain",
      "tsiolkovsky-1903"
    ],
    "pdf": "papers/electronics-wall.pdf"
  }
];
